In [1]:
#Dependencies
import pandas as pd
import numpy as np

In [2]:
#Data source
csv_path = 'purchase_data.csv'

In [3]:
#To Pandas data frame
Purchase_df = pd.read_csv(csv_path)

FileNotFoundError: [Errno 2] File b'purchase_data.csv' does not exist: b'purchase_data.csv'

In [4]:
#Total players count
total_players = len(Purchase_df["SN"].value_counts())

NameError: name 'Purchase_df' is not defined

In [5]:
#Data frame to show players count
total_number = pd.DataFrame({"Total Players":[total_players]})
total_number

   Total Players
0            576

In [6]:
#To get the number of unique items, average price, purchase count, and revenue for purchasing analysis
unique_items = len((Purchase_df["Item ID"]).unique())
average_price = (Purchase_df["Price"]).mean()
total_purchases = (Purchase_df["Purchase ID"]).count()
total_revenue = (Purchase_df["Price"]).sum()

In [7]:
#Data frame to show purchasing analysis
purchasing_analysis_df = pd.DataFrame({"Unique Items":[unique_items],
                           "Average Price":[average_price], 
                           "Total Number of Purchases": [total_purchases], 
                           "Total Revenue": [total_revenue]})
purchasing_analysis_df.style.format({'Average Price':"${:,.2f}",
                         'Total Revenue': '${:,.2f}'})

In [8]:
#Calculate gender demographics - percentages & counts of male, female & non-disclosed players
gender_groups = Purchase_df.groupby("Gender")
count_gender = gender_groups.nunique()["SN"]
players_percentage = count_gender / total_players * 100

In [9]:
#Data frame for gender demographics
gender_demographics = pd.DataFrame({"Percentage of Players": players_percentage, "Total Count": count_gender})
gender_demographics = pd.DataFrame({"Percentage of Players": players_percentage, "Total Count": count_gender})
gender_demographics.index.name = None

#Formatting
gender_demographics.sort_values(["Total Count"], ascending = False).style.format({"Percentage of Players":"{:.2f}"})

In [10]:
#Calculate purchase count, average purchase price, total purchase value, average purchase total per person by gender
purchase_count = gender_groups["Purchase ID"].count()
avg_purchase_price = gender_groups["Price"].mean()
avg_purchase_total = gender_groups["Price"].sum()
avg_purchase_per_person = avg_purchase_total/count_gender

In [11]:
#Data frame for purchase analysis by gender
gender_demographics = pd.DataFrame({"Purchase Count": purchase_count, 
                                    "Average Purchase Price": avg_purchase_price,
                                    "Average Purchase Value":avg_purchase_total,
                                    "Average Purchase Total per Person": avg_purchase_per_person}) 

#Formatting
gender_demographics.index.name = "Gender"
gender_demographics.style.format({"Average Purchase Value":"${:,.2f}",
                                  "Average Purchase Price":"${:,.2f}",
                                  "Avg Purchase Total per Person":"${:,.2f}"})

In [12]:
#Binning age demographics
age_bins = [0, 9.90, 14.90, 19.90, 24.90, 29.90, 34.90, 39.90, 99999]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [13]:
#Assigning bins
Purchase_df["Age Group"] = pd.cut(Purchase_df["Age"],age_bins, labels=group_names)
Purchase_df

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40+
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [14]:
#Adding new category "Age Group" and calculations for percentage of players and total count
age_grouped = Purchase_df.groupby("Age Group")
total_count_age = age_grouped["SN"].nunique()
percentage_by_age = (total_count_age/total_players) * 100

In [15]:
#Data frame for binned age demographics
age_demographics = pd.DataFrame({"Percentage of Players": percentage_by_age, "Total Count": total_count_age})

#Formatting
age_demographics.index.name = None
age_demographics.style.format({"Percentage of Players":"{:,.2f}"})

In [16]:
#Calculations for purchasing analysis by age group
purchase_by_age = age_grouped["Purchase ID"].count()
avg_purchase_age = age_grouped["Price"].mean()
total_purchases = age_grouped["Price"].sum()
avg_purchase_person_age = total_purchases/total_count_age

In [17]:
#Data frame for purchasing analysis by age
age_demographics = pd.DataFrame({"Purchase Count": purchase_by_age,
                                 "Average Purchase Price": avg_purchase_age,
                                 "Total Purchase Value":total_purchases,
                                 "Average Purchase Total per Person": avg_purchase_person_age})

# Formatting
age_demographics.index.name = None
age_demographics.style.format({"Average Purchase Price":"${:,.2f}",
                               "Total Purchase Value":"${:,.2f}",
                               "Average Purchase Total per Person":"${:,.2f}"})

In [18]:
# Grouping purchases by players and running basic calculations
top_spenders = Purchase_df.groupby("SN")
spender_purchase_count = top_spenders["Purchase ID"].count()
avg_purchase_price_spender = top_spenders["Price"].mean()
spender_total_purchase = top_spenders["Price"].sum()

In [19]:
#Data frame for top spenders
top_spender_stats = pd.DataFrame({"Purchase Count": spender_purchase_count,
                             "Average Purchase Price": avg_purchase_price_spender,
                             "Total Purchase Value":spender_total_purchase})

#Formatting
formatted_spenders = top_spender_stats.sort_values(["Total Purchase Value"], ascending=False).head()
formatted_spenders.style.format({"Average Purchase Total":"${:,.2f}",
                                 "Average Purchase Price":"${:,.2f}", 
                                 "Total Purchase Value":"${:,.2f}"})

In [20]:
#Data frame to include categories for calculating stats for most popular items
items = Purchase_df[["Item ID", "Item Name", "Price"]]
item_stats = items.groupby(["Item ID","Item Name"])
purchase_count_item = item_stats["Price"].count()
purchase_value = (item_stats["Price"].sum()) 
item_price = purchase_value/purchase_count_item

In [21]:
#Data frame for most popular items 
most_popular_items = pd.DataFrame({"Purchase Count": purchase_count_item, 
                                   "Item Price": item_price,
                                   "Total Purchase Value":purchase_value})

#Ascending style of data presentation
popular_formatted = most_popular_items.sort_values(["Purchase Count"], ascending=False).head()

#Formatting
popular_formatted.style.format({"Item Price":"${:,.2f}",
                                "Total Purchase Value":"${:,.2f}"})

In [22]:
#Data frame for most profitable items 
popular_formatted = most_popular_items.sort_values(["Total Purchase Value"],
                                                   ascending=False).head()
#Formatting
popular_formatted.style.format({"Item Price":"${:,.2f}",
                                "Total Purchase Value":"${:,.2f}"})